"""Template registry and initializer for project-level ``corvia.toml`` files."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Optional

from corvia.core.config import ConfigError, find_example_tomls


@dataclass(frozen=True)
class ConfigTemplate:
    id: str
    filename: str
    description: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


@dataclass(frozen=True)
class TemplateDetection:
    template_id: str
    confidence: int
    reasons: list[str]

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


_TEMPLATES: tuple[ConfigTemplate, ...] = (
    ConfigTemplate(
        id="minimal",
        filename="generated:minimal",
        description="Minimal portable config: enable preprocessing and cache only.",
    ),
    ConfigTemplate(
        id="ds5",
        filename="corvia.toml.ds5",
        description="Eclipse CDT / ARM DS-5 config using .cproject include extraction.",
    ),
    ConfigTemplate(
        id="ps5801",
        filename="corvia.toml.ps5801",
        description="Phison PS5801/PT5801 firmware config with SoC include paths.",
    ),
    ConfigTemplate(
        id="makefile",
        filename="generated:makefile",
        description="Makefile-backed config using Corvia's static/dry-run flag extraction.",
    ),
)

_TEMPLATE_BY_ID = {t.id: t for t in _TEMPLATES}


def list_config_templates() -> list[ConfigTemplate]:
    """Return supported config templates in stable display order."""
    return list(_TEMPLATES)


def _target_root(target: str | Path) -> Path:
    root = Path(target).expanduser().resolve()
    return root.parent if root.is_file() else root


def _limited_rglob(root: Path, pattern: str, max_hits: int = 20) -> list[Path]:
    hits: list[Path] = []
    try:
        for path in root.rglob(pattern):
            hits.append(path)
            if len(hits) >= max_hits:
                break
    except OSError:
        return hits
    return hits


def _path_mentions_phison(root: Path) -> bool:
    text = str(root).lower()
    return any(token in text for token in ("ps5801", "pt5801", "phison"))


def _detect_soc(root: Path, preferred_soc: Optional[str] = None) -> str:
    if preferred_soc:
        return preferred_soc.upper()

    for part in (p.upper() for p in root.parts):
        if part in {"PS5801", "PT5801"}:
            return part

    hw_root = root / "common" / "include" / "phison_hw"
    if hw_root.is_dir():
        for child in sorted(hw_root.iterdir()):
            if child.is_dir() and child.name.upper() in {"PS5801", "PT5801"}:
                return child.name.upper()

    return "PS5801"


def detect_config_templates(
    target: str | Path, *, ignore_existing: bool = False
) -> list[TemplateDetection]:
    """Return ordered template candidates with confidence and human-readable reasons.

    With ``ignore_existing=True`` an existing corvia.toml is disregarded, so
    real project-based detection runs (used by ``init_config(force=True)``).
    """
    root = _target_root(target)
    detections: list[TemplateDetection] = []

    if not ignore_existing:
        existing = root / "corvia.toml"
        if existing.is_file():
            return [TemplateDetection("existing", 100, [f"existing corvia.toml found at {existing}"])]

    if _limited_rglob(root, ".cproject", max_hits=1):
        detections.append(TemplateDetection("ds5", 95, [".cproject found under target tree"]))

    hw_root = root / "common" / "include" / "phison_hw"
    if hw_root.is_dir() or _path_mentions_phison(root):
        reasons = []
        if hw_root.is_dir():
            reasons.append("common/include/phison_hw exists")
        if _path_mentions_phison(root):
            reasons.append("target path mentions PS5801/PT5801/phison")
        detections.append(TemplateDetection("ps5801", 90, reasons))

    if (root / "Makefile").is_file() or (root / "makefile").is_file():
        detections.append(TemplateDetection("makefile", 75, ["Makefile found at target root"]))

    detections.append(TemplateDetection("minimal", 10, ["fallback when no project-specific template matches"]))
    return sorted(detections, key=lambda d: d.confidence, reverse=True)


def _template_file(filename: str) -> Optional[Path]:
    for path in find_example_tomls():
        if path.name == filename:
            return path
    return None


def _header(template_id: str, reasons: Iterable[str]) -> str:
    reason_text = "; ".join(reasons) or "manual selection"
    return (
        "# corvia.toml - generated by `corvia config init`\n"
        f"# template: {template_id}\n"
        f"# reason: {reason_text}\n"
        "# Review include paths and preprocessor defines before relying on final results.\n\n"
    )


def _posix_rel(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _collect_existing_dirs(root: Path, candidates: Iterable[Path]) -> list[str]:
    seen: set[str] = set()
    include_dirs: list[str] = []
    for candidate in candidates:
        if not candidate.is_dir():
            continue
        rel = _posix_rel(candidate, root)
        if rel not in seen:
            seen.add(rel)
            include_dirs.append(rel)
    return include_dirs


def _render_include_list(include_dirs: list[str]) -> str:
    if not include_dirs:
        return '# include = ["path/to/headers"]'
    body = "\n".join(f'    "{p}",' for p in include_dirs)
    return "include = [\n" + body + "\n]"


def _render_minimal(reasons: Iterable[str]) -> str:
    return _header("minimal", reasons) + """[paths]
use_cpp = true
# include = ["path/to/headers"]
# cproject = ".cproject"   # Eclipse CDT: auto-extract include paths
# makefile = "Makefile"    # Makefile: auto-extract -I/-D flags

[cache]
enabled = true
dir = ".corvia_cache"
"""


def _render_makefile(reasons: Iterable[str]) -> str:
    return _header("makefile", reasons) + """[paths]
use_cpp = true
makefile = "Makefile"
# make_target = "all"
# make_args = ["SOC_ID=PS5801"]

[cache]
enabled = true
dir = ".corvia_cache"
"""


def _render_ds5(reasons: Iterable[str]) -> str:
    template = _template_file("corvia.toml.ds5")
    if template and template.is_file():
        return _header("ds5", reasons) + template.read_text(encoding="utf-8")
    return _header("ds5", reasons) + """[paths]
use_cpp = true
cproject = ".cproject"

[severity]
"parser" = "warning"

[cache]
enabled = true
dir = ".corvia_cache"
"""


def _render_ps5801(root: Path, reasons: Iterable[str], soc: Optional[str]) -> str:
    soc_id = _detect_soc(root, preferred_soc=soc)
    hw_root = root / "common" / "include" / "phison_hw"
    sal_root = root / "common" / "sal"

    candidates: list[Path] = [
        root / "common" / "sal",
        root / "common" / "config",
        root / "common" / "include",
        root / "common" / "include" / "phison_hw",
        root / "common" / "include" / "phison_hw" / "uart",
        root / "common" / "include" / "phison_hw" / soc_id,
    ]
    if sal_root.is_dir():
        candidates.extend(sorted(p for p in sal_root.rglob("*") if p.is_dir()))
    soc_root = hw_root / soc_id
    if soc_root.is_dir():
        candidates.extend(sorted(p for p in soc_root.rglob("*") if p.is_dir()))

    include_dirs = _collect_existing_dirs(root, candidates)
    if not include_dirs:
        template = _template_file("corvia.toml.ps5801")
        if template and template.is_file():
            return _header("ps5801", reasons) + template.read_text(encoding="utf-8").replace("PS5801", soc_id)

    return _header("ps5801", reasons) + f"""# SOC_ID: {soc_id}

[paths]
use_cpp = true

{_render_include_list(include_dirs)}

cpp_args = "-DSOC_ID={soc_id} -DPS5801=2 -DPT5801=1"

[output]
format = "text"

[cache]
enabled = true
dir = ".corvia_cache"
"""


def render_config_template(
    template_id: str,
    target: str | Path = ".",
    *,
    reasons: Optional[Iterable[str]] = None,
    soc: Optional[str] = None,
) -> str:
    """Render a corvia.toml template for ``target`` without writing it."""
    root = _target_root(target)
    reason_list = list(reasons or [])
    if template_id == "auto":
        detected = detect_config_templates(root)[0]
        template_id = detected.template_id
        reason_list = detected.reasons
    if template_id == "existing":
        raise ConfigError("existing corvia.toml is not a renderable template")
    if template_id not in _TEMPLATE_BY_ID:
        raise ConfigError(f"Unknown config template '{template_id}'")

    if template_id == "minimal":
        return _render_minimal(reason_list)
    if template_id == "makefile":
        return _render_makefile(reason_list)
    if template_id == "ds5":
        return _render_ds5(reason_list)
    if template_id == "ps5801":
        return _render_ps5801(root, reason_list, soc=soc)
    raise ConfigError(f"Unknown config template '{template_id}'")


def init_config(
    target: str | Path = ".",
    *,
    template_id: str = "auto",
    force: bool = False,
    dry_run: bool = False,
    soc: Optional[str] = None,
) -> dict[str, object]:
    """Create ``corvia.toml`` for ``target`` and return a JSON-friendly summary."""
    root = _target_root(target)
    root.mkdir(parents=True, exist_ok=True)
    dest = root / "corvia.toml"
    if dest.exists() and not force:
        raise ConfigError(f"{dest} already exists; pass --force to overwrite")

    # With force=True the existing corvia.toml is being overwritten, so run
    # detection against the project itself (the "existing" pseudo-template
    # is not renderable and would make template_id="auto" fail).
    detections = detect_config_templates(root, ignore_existing=force)
    selected = template_id
    reasons = ["manual selection"]
    confidence = None
    if template_id == "auto":
        selected_detection = next(
            (d for d in detections if d.template_id != "existing"), None
        )
        if selected_detection is None:
            # Nothing but the existing-file marker detected: fall back to
            # the always-valid minimal template.
            selected_detection = TemplateDetection(
                "minimal", 10, ["fallback when only an existing corvia.toml was detected"]
            )
        selected = selected_detection.template_id
        reasons = selected_detection.reasons
        confidence = selected_detection.confidence

    content = render_config_template(selected, root, reasons=reasons, soc=soc)
    if not dry_run:
        dest.write_text(content, encoding="utf-8")

    return {
        "target": str(root),
        "path": str(dest),
        "template": selected,
        "confidence": confidence,
        "reasons": reasons,
        "dry_run": dry_run,
        "written": not dry_run,
        "content": content if dry_run else None,
    }


def dumps_json(data: object) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2)
