"""Markdown report generator."""

from __future__ import annotations

from corvia.models import AnalysisResult
from corvia.reporters.base import BaseReporter


class MdReporter(BaseReporter):
    def generate(self, result: AnalysisResult) -> str:
        from corvia import __version__
        data = result.to_dict()
        summary = data["summary"]
        lines: list[str] = []

        lines.append("# CORVIA Analysis Report\n")
        lines.append(f"**CORVIA v{__version__}** | Files analyzed: {summary['total_files']} | Total issues: {summary['total_issues']}\n")

        lines.append("## Summary\n")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        lines.append(f"| Error    | {summary['ERROR']} |")
        lines.append(f"| Warning  | {summary['WARNING']} |")
        lines.append(f"| Info     | {summary['INFO']} |")
        lines.append(f"| **Total** | **{summary['total_issues']}** |")
        lines.append("")

        misra = data["misra_summary"]
        if misra:
            lines.append("## MISRA C:2012 Rule Summary\n")
            lines.append("| Rule | Category | Violations | Description |")
            lines.append("|------|----------|------------|-------------|")
            for rid, rule in misra.items():
                lines.append(f"| {rule['rule_id']} | {rule['category']} | {rule['violations']} | {rule['description']} |")
            lines.append("")

        if data["issues"]:
            lines.append("## Issues\n")

            errors = [i for i in data["issues"] if i["severity"] == "ERROR"]
            warnings = [i for i in data["issues"] if i["severity"] == "WARNING"]
            infos = [i for i in data["issues"] if i["severity"] == "INFO"]

            for severity_name, issues in [("Errors", errors), ("Warnings", warnings), ("Info", infos)]:
                if not issues:
                    continue
                lines.append(f"### {severity_name} ({len(issues)})\n")
                lines.append("| Location | Checker | MISRA Rule | Message |")
                lines.append("|----------|---------|------------|---------|")
                for issue in issues:
                    loc = f"`{issue['file']}:{issue['line']}:{issue['column']}`"
                    checker = f"`{issue['checker_id']}`"
                    misra_rule = ""
                    if issue.get("misra_rule"):
                        mr = issue["misra_rule"]
                        misra_rule = f"Rule {mr['rule_id']} ({mr['category']})"
                    lines.append(f"| {loc} | {checker} | {misra_rule} | {issue['message']} |")
                lines.append("")

        lines.append("---\n")
        lines.append(f"*Generated by CORVIA v{__version__}*\n")

        return "\n".join(lines)
