"""HTML report generator with self-contained CSS."""

from __future__ import annotations

from jinja2 import Template

from covia.models import AnalysisResult
from covia.reporters.base import BaseReporter

_HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>COVIA Analysis Report</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; padding: 20px; }
.container { max-width: 1200px; margin: 0 auto; }
h1 { font-size: 24px; margin-bottom: 20px; color: #1a1a1a; }
h2 { font-size: 18px; margin: 20px 0 10px; color: #1a1a1a; }
.summary { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
.card { background: white; border-radius: 8px; padding: 16px 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); min-width: 140px; }
.card .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
.card .value { font-size: 28px; font-weight: 700; margin-top: 4px; }
.card .value.error { color: #dc3545; }
.card .value.warning { color: #ffc107; }
.card .value.info { color: #0d6efd; }
table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 24px; }
th { background: #f8f9fa; text-align: left; padding: 10px 14px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #666; border-bottom: 2px solid #dee2e6; }
td { padding: 10px 14px; border-bottom: 1px solid #eee; font-size: 14px; }
tr:hover td { background: #f8f9fa; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; }
.badge.error { background: #f8d7da; color: #842029; }
.badge.warning { background: #fff3cd; color: #664d03; }
.badge.info { background: #cff4fc; color: #055160; }
.badge.mandatory { background: #f8d7da; color: #842029; }
.badge.required { background: #fff3cd; color: #664d03; }
.badge.advisory { background: #d1e7dd; color: #0f5132; }
.mono { font-family: 'SF Mono', Consolas, monospace; font-size: 13px; }
.misra-tag { font-size: 11px; color: #6c757d; }
footer { text-align: center; padding: 20px; color: #999; font-size: 12px; }
</style>
</head>
<body>
<div class="container">
<h1>COVIA Analysis Report</h1>

<div class="summary">
  <div class="card"><div class="label">Files Analyzed</div><div class="value">{{ summary.total_files }}</div></div>
  <div class="card"><div class="label">Total Issues</div><div class="value">{{ summary.total_issues }}</div></div>
  <div class="card"><div class="label">Errors</div><div class="value error">{{ summary.ERROR }}</div></div>
  <div class="card"><div class="label">Warnings</div><div class="value warning">{{ summary.WARNING }}</div></div>
  <div class="card"><div class="label">Info</div><div class="value info">{{ summary.INFO }}</div></div>
</div>

{% if misra_summary %}
<h2>MISRA C:2012 Rule Summary</h2>
<table>
<thead><tr><th>Rule</th><th>Category</th><th>Violations</th><th>Description</th></tr></thead>
<tbody>
{% for rid, rule in misra_summary.items() %}
<tr>
  <td class="mono">{{ rule.rule_id }}</td>
  <td><span class="badge {{ rule.category | lower }}">{{ rule.category }}</span></td>
  <td>{{ rule.violations }}</td>
  <td>{{ rule.description }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

<h2>Issues ({{ issues | length }})</h2>
<table>
<thead><tr><th>Severity</th><th>Location</th><th>Checker</th><th>MISRA Rule</th><th>Message</th></tr></thead>
<tbody>
{% for issue in issues %}
<tr>
  <td><span class="badge {{ issue.severity | lower }}">{{ issue.severity }}</span></td>
  <td class="mono">{{ issue.file }}:{{ issue.line }}:{{ issue.column }}</td>
  <td class="mono">{{ issue.checker_id }}</td>
  <td class="mono">{% if issue.misra_rule %}<span class="misra-tag">Rule {{ issue.misra_rule.rule_id }}</span>{% endif %}</td>
  <td>{{ issue.message }}</td>
</tr>
{% endfor %}
</tbody>
</table>

<footer>Generated by COVIA v{{ version }} &mdash; C Language Static Analysis Tool</footer>
</div>
</body>
</html>
""")


class HtmlReporter(BaseReporter):
    def generate(self, result: AnalysisResult) -> str:
        from covia import __version__
        data = result.to_dict()
        return _HTML_TEMPLATE.render(
            summary=data["summary"],
            misra_summary=data["misra_summary"],
            issues=data["issues"],
            version=__version__,
        )
